module.exports = {
  // extends: 'stylelint-config-recommended',
  plugins: ['stylelint-scss'],
  rules: {
    'block-closing-brace-newline-after': [
      'always',
      // Ignore @if … @else in scss
      { ignoreAtRules: ['if', 'else'] }
    ],
    'block-no-empty': true,
    'block-opening-brace-space-before': 'always',
    'color-hex-case': 'lower',
    'color-hex-length': 'short',
    'color-named': 'never',
    'comment-no-empty': true,
    'declaration-bang-space-after': 'never',
    'declaration-bang-space-before': 'always',
    'declaration-block-no-duplicate-properties': true,
    'declaration-block-no-redundant-longhand-properties': true,
    'declaration-block-single-line-max-declarations': 1,
    'declaration-block-trailing-semicolon': 'always',
    'declaration-colon-space-after': 'always',
    'declaration-colon-space-before': 'never',
    'declaration-property-value-blacklist': [
      { '/^border/': ['none'] },
      { severity: 'error' }
    ],
    'declaration-no-important': true,
    'font-family-no-duplicate-names': true,
    'function-calc-no-unspaced-operator': true,
    'function-comma-space-after': 'always',
    'function-linear-gradient-no-nonstandard-direction': true,
    'function-parentheses-space-inside': 'never',
    'function-url-quotes': 'always',
    // prettier-ignore
    'indentation': [4, { severity: 'warning' }],
    'length-zero-no-unit': true,
    'max-nesting-depth': 3,
    'media-feature-name-no-unknown': true,
    'no-empty-source': true,
    'no-eol-whitespace': true,
    'no-extra-semicolons': true,
    'no-missing-end-of-source-newline': true,
    'number-no-trailing-zeros': true,
    'number-leading-zero': 'always',
    'property-case': 'lower',
    'property-no-unknown': true,
    'property-no-vendor-prefix': true,
    'rule-empty-line-before': [
      'always',
      { except: ['after-single-line-comment', 'first-nested'] }
    ],
    'scss/at-else-empty-line-before': 'never',
    'scss/at-import-no-partial-leading-underscore': true,
    'scss/at-import-partial-extension-blacklist': ['scss'],
    'scss/at-rule-no-unknown': true,
    'scss/media-feature-value-dollar-variable': 'always',
    'scss/selector-no-redundant-nesting-selector': true,
    'selector-list-comma-newline-after': 'always',
    'selector-max-id': 0,
    'selector-no-qualifying-type': [true, { ignore: ['attribute', 'class'] }],
    'selector-pseudo-element-no-unknown': true,
    'selector-type-no-unknown': true,
    'string-no-newline': true,
    'string-quotes': 'single',
    'unit-case': 'lower',
    'unit-no-unknown': true,
    'value-no-vendor-prefix': true
  }
};
